blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<article_id>[0-9]+)/$', views.article_detail, name='article_detail'),
	url(r'^categories/$', views.categories, name='categories'),
	url(r'^category/(?P<category_name>[a-zA-Z]+)/$', views.category_detail, name='category_detail'),
]

firstblood/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=255)
	slug = models.CharField(max_length=255)
	def __str__(self):
		return self.name
	def the_name(self):
		return self.name
	def articles(self):
		articles = Article.objects.filter(category_id=self.id)
		return articles
class Article(models.Model):
	title = models.CharField(max_length=255)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	content = models.TextField()
	created = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title
	def the_title(self):
		return self.title
	def the_content(self):
		return self.content
	def the_category(self):
		return self.category
	def created_at(self):
		return self.created

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from .models import Article, Category
# Create your views here.
def index(request):
	#return HttpResponse("hello, It's me")
	articles = Article.objects.all().order_by('category_id')
	return HttpResponse(loader.get_template('blog/index.html').render({'articless': articles}))

def article_detail(request, article_id):
	article 			= Article.objects.get(pk=article_id)
	related_articles 	= Article.objects.filter(category_id=article.category.id)
	template 		= loader.get_template('blog/detail.html')
	context 		= RequestContext(request, {
		'article': article,
		'related_articles': related_articles,
	})
	return HttpResponse(template.render(context))

def categories(request):
	categories = Category.objects.all()
	return HttpResponse(loader.get_template('blog/categories.html').render({'categories': categories}));
def category_detail(request, category_name):
	if category_name:
		category = Category.objects.get(slug=category_name)
		if category:
			result = {
				'status': 200,
				'data': category,
			}
		else:
			result = {
				'status' : 404,
				'message': 'Not found category \"%s\"' %category_name
			}
	return HttpResponse(loader.get_template('blog/category_detail.html').render(result));

blog/templates/blog/categories.html
<h1>Categories on site</h1>
<ul>
{% if categories %}
	{% for category in categories %}
		<li><a href="{% url 'blog:category_detail' category.slug%}">{{ category.name }}</a> ({{ category.articles.count }} articles)</li>
	{% endfor %}
{% endif %}
</ul>
<hr>
<a href="{% url 'blog:index' %}">Back to Home</a>

blog/templates/blog/category_detail.html
{% if status = 200 %}
	<h1>Category: {{ data.name }}</h1>
	<ul>
		{% for article in data.articles %}
			<li><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	{{ message }}
{% endif %}
<hr>
<a href="{% url 'blog:categories' %}">Back to Home</a>

blog/templates/blog/detail.html
<h1>{{ article.title }}</h1>
<p>Category: <a href="{% url 'blog:category_detail' article.category.slug %}">{{ article.category.name }}</a></p>
<p>{{ article.content }}</p>
<p>Created at {{ article.created_at }}</p>
<hr>
<p>Related articles:</p>
<ul>
	{% if related_articles %}
		{% for a in related_articles%}
			<li><a href="{% url 'blog:article_detail' a.id %}">{{ a.title }}</a></li>
		{% endfor%}
	{% endif %}
</ul>
<hr>
<a href="{% url 'blog:index' %}">Back to Home</a>

blog/templates/blog/index.html
<h1>hello world!</h1>
{% if articless %}
	{% for article in articless %}
		<ul>
			<li><a href="/blog/{{ article.id }}">{{ article.title }}</a></li>
			<li>in {{ article.category.name }}</li>
		</ul>
		<hr>
	{% endfor %}
{% endif %}